### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by mstenflo** [mstenflo/icook#2]
Please review my user login and signup

**Comment by samwalker191** [comment]
Looks good! Please see my recommendations below:

1. I'm not able to sign up or login. Make sure it works!
2. Demo user isn't able to login either
3. errors don't show up when attempting to submit the form with bad data

![image](https://user-images.githubusercontent.com/49164119/72189343-739b3180-33b1-11ea-8306-49fe03e1c1b0.png)

_______________________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/49164119/72189352-77c74f00-33b1-11ea-8ccc-f65b9dae159b.png)

_______________________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/49164119/72189364-7ac23f80-33b1-11ea-83d7-13eb7f09baab.png)

_______________________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/49164119/72189371-7dbd3000-33b1-11ea-93ec-fc68c62499c5.png)

_______________________________________________________________________________________________________________

**Comment by samwalker191** [comment]
Looks better! I found a few things that you should fix. Please see below:

1. errors still show when you fail to login, then switch to the sign up page.
2. Your spacing for the footer should look more like the spacing they have. I attached a screenshot of theirs.

![image](https://user-images.githubusercontent.com/49164119/72283606-f4497000-35f3-11ea-8bb1-6c0ca35bbf9a.png)

 ---

![image](https://user-images.githubusercontent.com/49164119/72283618-fca1ab00-35f3-11ea-9cc0-a4517de192b2.png)

---

![image](https://user-images.githubusercontent.com/49164119/72283625-ff9c9b80-35f3-11ea-9e99-0429ca574b32.png)

**Comment by mstenflo** [comment]
Thanks for the feedback, I update the changes to heroku
